services:
  - type: web
    name: shivaa-om-globe-trade
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production